const fs = require('fs');
const p1 = 'C:/Users/dbatc/Downloads/data-structure-migration/components/clients/clients-table.tsx';
const p2 = 'C:/Users/dbatc/Downloads/data-structure-migration/components/clients/client-charts.tsx';

const table = [
  "\"use client\"",
  "",
  "import { useState, useMemo } from \"react\"",
  "import { useRouter } from \"next/navigation\"",
  "import { Star, ChevronDown, ChevronUp, Search } from \"lucide-react\"",
  "import { cn } from \"@/lib/utils\"",
  "import { SelectField } from \"@/components/shared/select-field\"",
  "import { useAirtable } from \"@/hooks/use-airtable\"",
  "import { parseCurrency } from \"@/lib/transforms\"",
  "",
  "type SortKey = \"brand\" | \"totalPaid\" | \"monthlyPrice\"",
  "",
  "const statusCfg: Record<string, string> = {",
  "  Active: \"bg-emerald-50 text-emerald-700 border-emerald-200\",",
  "  Inactive: \"bg-amber-50 text-amber-700 border-amber-200\",",
  "}",
  "",
  "const planCfg: Record<string, string> = {",
  "  \"2 Tests\": \"bg-sky-50 text-sky-700 border-sky-200\",",
  "  \"3 Tests\": \"bg-violet-50 text-violet-700 border-violet-200\",",
  "  \"1 Test\": \"bg-teal-50 text-teal-700 border-teal-200\",",
  "  Course: \"bg-amber-50 text-amber-700 border-amber-200\",",
  "}",
  "",
  "function Stars({ count }: { count: number | null }) {",
  "  if (!count) return <span className=\"text-muted-foreground\">-</span>",
  "  return (",
  "    <div className=\"flex items-center gap-0.5\">",
  "      {Array.from({ length: 5 }).map((_, i) => (",
  "        <Star",
  "          key={i}",
  "          className={cn(\"h-3.5 w-3.5\", i < count ? \"fill-amber-400 text-amber-400\" : \"text-border fill-transparent\")}",
  "        />",
  "      ))}",
  "    </div>",
  "  )",
  "}",
  "",
  "export function ClientsTable() {",
  "  const router = useRouter()",
  "  const [sortKey, setSortKey] = useState<SortKey>(\"totalPaid\")",
  "  const [sortDir, setSortDir] = useState<\"asc\" | \"desc\">(\"desc\")",
  "  const [statusFilter, setStatusFilter] = useState<string>(\"All Status\")",
  "  const [planFilter, setPlanFilter] = useState<string>(\"All Plans\")",
  "  const [searchQuery, setSearchQuery] = useState<string>(\"\")",
  "",
